repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.0
    hooks:
    - id: flake8
      exclude: ^tests/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
        - id: mypy
          exclude: ^examples/

#-   repo: local
#    hooks:
#        - id: pytest-check
#          name: pytest-check
#          entry: bash -c 'pytest tests -v'
#          language: system