name: Code check
on: [push]
jobs:
  code_checks:
    name: Linters and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.15
      - name: Install dependencies
        run: |
          make install-req
          make install-pc
      - name: Run linters and tests
        run: make pc